# Generated by Django 6.1.1 on 2026-09-24 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrearsrecord',
            name='paid_in_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrears_paid', to='payroll_app.payrollrun'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='email_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='notification_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='preferred_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='sms_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('SALARY', 'Salary')], max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('INACTIVE', 'Inactive')], default='UNVERIFIED', max_length=10),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this run. Legacy runs are back-filled from their lines.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='payroll_app.company'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='arrears',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='conveyance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='days_in_month',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='esi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='lop_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='lop_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='payslip_number',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='reimbursements',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='paid_in_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements_paid', to='payroll_app.payrollrun'),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='reimbursement_receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('REGISTRATION', 'Registration')], default='REGISTRATION', max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_holder_name', models.CharField(blank=True, max_length=150)),
                ('account_no', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('mode', models.CharField(choices=[('NEFT', 'NEFT'), ('IMPS', 'IMPS'), ('RTGS', 'RTGS'), ('OTHER', 'Other')], default='NEFT', max_length=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'Initiated'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('reference_number', models.CharField(blank=True, help_text='Bank UTR / transaction reference', max_length=60)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_payments', to='payroll_app.company')),
                ('payroll_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_payment', to='payroll_app.payrollrunline')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference_number', ''), _negated=True), fields=('reference_number',), name='unique_bank_payment_reference')],
            },
        ),
    ]
