# Generated by Django 6.1.1 on 2026-09-22 05:23

import payroll_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrunline',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='payment_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Registration'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('PROCESS_PAYROLL', 'Payroll Processing'), ('PAYMENT_STATUS_CHANGE', 'Payment Status Change'), ('EXPORT', 'Export'), ('OTHER', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(help_text='e.g. EMP0001', max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentdeclaration',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='investment_proofs/%Y/%m/', validators=[payroll_app.models.validate_proof_document]),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'employee_code'), name='unique_employee_code_per_company'),
        ),
    ]
