# Generated by Django 5.2.15 on 2026-09-28 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0002_payrollrunline_failure_reason_and_more'),
        ('payroll_app', '0003_backfill_existing_data'),
    ]

    operations = [
    ]
