# Generated by Django 5.2.15 on 2026-10-01 06:08

import django.db.models.deletion
import django.utils.timezone
import payroll_app.models_features
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_merge_20260928_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_demo_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='industry',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='modules',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='request_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approver_comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='insurance_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='loan_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'New'), ('CONTACTED', 'Contacted'), ('DEMO_SCHEDULED', 'Demo scheduled'), ('DEMO_COMPLETED', 'Demo completed'), ('FOLLOW_UP', 'Follow-up required'), ('CONVERTED', 'Converted'), ('CLOSED', 'Closed'), ('APPROVED', 'Approved (legacy)'), ('REJECTED', 'Rejected (legacy)')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=3000)),
                ('audience', models.CharField(choices=[('ALL', 'Everyone in the company'), ('EMPLOYEES', 'Employees only')], default='ALL', max_length=10)),
                ('publish_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='payroll_app.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoRequestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='payroll_app.demorequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('FORM16', 'Form 16'), ('FORM22', 'Form 22'), ('FORM12BB', 'Form 12BB'), ('OTHER', 'Other document')], max_length=10)),
                ('financial_year', models.CharField(help_text='e.g. 2025-26', max_length=9)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('file_name', models.CharField(max_length=200)),
                ('content_type', models.CharField(default='application/pdf', max_length=100)),
                ('data', models.BinaryField()),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='payroll_app.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='payroll_app.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-financial_year', 'doc_type', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('category', models.CharField(choices=[('PAYROLL', 'Salary / Payroll'), ('ATTENDANCE', 'Attendance / Leave'), ('WORKPLACE', 'Workplace'), ('HARASSMENT', 'Harassment'), ('IT', 'IT / Systems'), ('OTHER', 'Other')], max_length=12)),
                ('subject', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=3000)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='grievances/%Y/%m/', validators=[payroll_app.models_features.validate_attachment])),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grievances', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to='payroll_app.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to='payroll_app.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrievanceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('old_status', models.CharField(blank=True, max_length=12)),
                ('new_status', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='payroll_app.grievance')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=120)),
                ('policy_number', models.CharField(max_length=60)),
                ('policy_type', models.CharField(blank=True, help_text='e.g. Group health, Term life', max_length=60)),
                ('sum_insured', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee_premium_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employer_contribution_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='payroll_app.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='payroll_app.employee')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=40)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='% per year (information only)', max_digits=5)),
                ('tenure_months', models.PositiveSmallIntegerField()),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(help_text='First month the EMI is deducted')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=6)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='payroll_app.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='payroll_app.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_repayments', to='payroll_app.payrollrunline')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='payroll_app.loan')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_monthly_gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_monthly_gross', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for "and above"', max_digits=10, null=True)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('february_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional different amount for February', max_digits=8, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_slabs', to='payroll_app.company')),
            ],
            options={
                'ordering': ['min_monthly_gross'],
            },
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(fields=('company', 'reference_no'), name='unique_loan_ref_per_company'),
        ),
        migrations.AddConstraint(
            model_name='loanrepayment',
            constraint=models.UniqueConstraint(fields=('loan', 'line'), name='one_repayment_per_loan_per_line'),
        ),
    ]
