# Generated by Django 5.2.15 on 2026-10-01 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0007_phase4_shifts_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (not visible to employee)'), ('PENDING', 'Awaiting verification'), ('VERIFIED', 'Available'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal loan'), ('SALARY_ADVANCE', 'Salary advance'), ('VEHICLE', 'Vehicle loan'), ('HOUSING', 'Housing loan'), ('OTHER', 'Other')], default='PERSONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='paycomponent',
            name='calc_type',
            field=models.CharField(choices=[('FIXED', 'Fixed amount'), ('PERCENT_BASIC', '% of basic')], default='FIXED', max_length=14),
        ),
        migrations.AddField(
            model_name='paycomponent',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Used when calculated as % of basic', max_digits=5),
        ),
        migrations.AddField(
            model_name='professionaltaxslab',
            name='state',
            field=models.CharField(blank=True, help_text='State / region these slabs apply to (for reference)', max_length=40),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='approver_comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='doc_type',
            field=models.CharField(choices=[('FORM16', 'Form 16'), ('FORM22', 'Form 22'), ('FORM12BB', 'Form 12BB'), ('ID_PROOF', 'ID proof'), ('ADDRESS', 'Address proof'), ('EDUCATION', 'Education certificate'), ('EXPERIENCE', 'Experience letter'), ('OTHER', 'Other document')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('EARNED', 'Earned Leave'), ('UNPAID', 'Unpaid Leave (loss of pay)'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('COMP_OFF', 'Compensatory Off')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paycomponent',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='payroll_app.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('announcement', 'user'), name='one_read_per_user')],
            },
        ),
    ]
