# Generated by Django 6.1.1 on 2026-10-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0008_phase5_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Goes up by 1 every time the record is saved. Used to detect two people editing at once.'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Goes up by 1 every time the record is saved. Used to detect two people editing at once.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Goes up by 1 every time the record is saved. Used to detect two people editing at once.'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Goes up by 1 every time the record is saved. Used to detect two people editing at once.'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Goes up by 1 every time the record is saved. Used to detect two people editing at once.'),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Goes up by 1 every time the record is saved. Used to detect two people editing at once.'),
        ),
    ]
