# Generated by Django 6.1.1 on 2026-10-08 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0009_record_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard calendar', max_length=80)),
                ('weekly_off_days', models.CharField(default='6', help_text='Weekly offs as weekday numbers, comma separated: 0=Monday ... 5=Saturday, 6=Sunday', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text="The company's default calendar")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_calendars', to='payroll_app.company')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cycle_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=10)),
                ('payroll_month', models.CharField(help_text='e.g. October 2026', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('processing_date', models.DateField(blank=True, null=True)),
                ('pay_date', models.DateField(blank=True, help_text='Salary pay date', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('LOCKED', 'Locked')], default='DRAFT', max_length=12)),
                ('salary_policy', models.CharField(choices=[('WORKING_DAYS', 'Working days from the Working Calendar'), ('CALENDAR_DAYS', 'Calendar days of the period (the original method)')], default='WORKING_DAYS', max_length=14)),
                ('unmarked_as_lop', models.BooleanField(default=False, help_text='Count working days with no attendance record (and no approved leave) as loss of pay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_cycles', to='payroll_app.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_cycles_created', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_cycle', to='payroll_app.payrollrun')),
                ('calendar', models.ForeignKey(blank=True, help_text="Leave empty to use each employee's calendar or the company default", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_cycles', to='payroll_app.workingcalendar')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_assignment', to='payroll_app.employee')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='payroll_app.workingcalendar')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_type', models.CharField(choices=[('PUBLIC_HOLIDAY', 'Public holiday'), ('COMPANY_HOLIDAY', 'Company holiday'), ('OPTIONAL_HOLIDAY', 'Optional holiday (working day)'), ('SPECIAL_WORKING', 'Special working day'), ('HALF_DAY', 'Half working day (counts as a working day)')], default='PUBLIC_HOLIDAY', max_length=20)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='payroll_app.workingcalendar')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddConstraint(
            model_name='workingcalendar',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_calendar_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='workingcalendar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('company',), name='one_default_calendar_per_company'),
        ),
        migrations.AddConstraint(
            model_name='paycycle',
            constraint=models.UniqueConstraint(fields=('company', 'start_date', 'end_date'), name='unique_pay_period_per_company'),
        ),
        migrations.AddConstraint(
            model_name='paycycle',
            constraint=models.UniqueConstraint(condition=models.Q(('cycle_type', 'MONTHLY')), fields=('company', 'payroll_month'), name='one_monthly_cycle_per_month'),
        ),
        migrations.AddConstraint(
            model_name='calendarday',
            constraint=models.UniqueConstraint(fields=('calendar', 'date'), name='one_entry_per_calendar_date'),
        ),
    ]
